json.id project.id
json.title project.title
json.current_funding project.current_funding
json.funding_goal project.funding_goal
json.funded project.funded
json.summary project.summary
json.body project.body
json.creator_id project.creator_id
json.deadline project.deadline
json.category project.category
json.subcategory project.category
json.image asset_path(project.image.url)
